name: "Python Hello Action"
description: "A simple GitHub Action using Python"

inputs:
  name:
    description: "Your name"
    required: true
    default: "Developer"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"

    - name: Debug Inputs
      shell: bash
      run: echo "INPUT_NAME=${{ inputs.name }}"

    - name: Run Python Script
      shell: bash
      env:
        INPUT_NAME: ${{ inputs.name }}  # ✅ Explicitly setting INPUT_NAME
      run: python $GITHUB_ACTION_PATH/hello.py