name: Test Custom Python Action

on: [push]

jobs:
  run_python_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  # 🔹 This step is mandatory
        uses: actions/checkout@v4

      - name: Run custom Python action
        uses: ./github/actions/hello  # 🔹 Correct relative path
        with:
          name: "GitHub User"