name: demo4
on:
    workflow_dispatch:
    push:
jobs:
    check-the-application:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ls -lart
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm install
            - run: npm start &
            - run: sleep 5
            # Check if the app is running on port 3000
            - run: |
                if lsof -i :3000 > /dev/null 2>&1; then
                echo "Application is running on port 3000"
                else
                echo "Application is NOT running on port 3000. Checking logs..."
                exit 1
                fi