name: Test Custom Python Action

on: [push]

jobs:
  run_python_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -lart # Recursively list files to verify action location

      - name: Run custom Python action
        uses: ./github/actions/hello 
        with:
          name: "GitHub User"